rootProject.name = "CloudstreamPlugins"

// Chaturbate + Stripchat + Cam4 + BongaCams + Camsoda + Streamate providers.
include("CoomerProvider")
include("PornTubeProvider")
include("PornhubProvider")
include("ChaturbateProvider")
include("ChaturbateFStremioProvider")
include("ChaturbateMStremioProvider")
include("ChaturbateTStremioProvider")
include("StripchatGirlsStremioProvider")
include("StripchatManStremioProvider")
include("StripchatTransStremioProvider")
include("StripchatProvider")
include("Cam4Provider")
include("BongaCamsProvider")
include("CamsodaProvider")
include("StreamateProvider")
// Doppiocam-family + room-scrape + wonStore + web-rtc providers.
include("XhamsterliveProvider")
include("FikfapcamsProvider")
include("MestripProvider")
include("FreecamsProvider")
include("CamsProvider")
include("SinpartyProvider")
